spring:
   profiles: dev
server:
   port: 8087

---
spring:
   profiles: qat
server:
   port: 9091
   
---
spring:
   profiles: uat
server:
   port: 9092
   
---
spring: 
   profiles: prod
server: 
   port: 4431